In [45]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import reader
import tensorflow_datasets as tfds
import numpy as np
import os
import pickle

In [46]:
file_name = 'select_description_from_sys_district.csv'
if reader.check_file(file_name, url=''):
    hotelDescs = reader.read_data_as_text(file_name)
else:
    quit()

文件  select_description_from_sys_district.csv 存在。盛宴大幕拉开了。


In [48]:
with open(os.path.join('datasets','select_description_from_sys_district.csv')) as data_f:
    trainX, trainY, testX, testY, vocabulary_index2word=pickle.load(data_f)
    vocab_size=len(vocabulary_index2word)  

TypeError: a bytes-like object is required, not 'str'

In [44]:
def labeler(example, index):
    return example, tf.cast(index, tf.int64) 

if not os.path.exists(os.path.join('datasets',file_name)):
    print('文件',file_name, '不存在，请确保文件在datasets目录下。')
    #file_name = urlretrieve(url + file_name, dir_name + os.sep + file_name)
else:
    print('文件 ',file_name, '存在。盛宴大幕拉开了。')


data=np.loadtxt(os.path.join('datasets','select_description_from_sys_district.csv'),delimiter=',')
X_train=data[:,0]
y_train=data[:,1]
print(X_train)
# def readMyFileFormat(fileNameQueue):
#     reader = tf.compat.v1.TextLineReader()
#     key, value = reader.read(fileNameQueue)
#     record_defaults = [[1], [1], [1]]
#     col1, col2, col3 = tf.decode_csv(value, record_defaults = record_defaults)
#     features = tf.pack([col1, col2])
#     label = col3
#     return features, label

# example, label = readMyFileFormat([os.path.join('datasets','select_description_from_sys_district.csv')])

# labeled_data_sets = []
# lines_dataset = tf.data.TextLineDataset(os.path.join('datasets','select_description_from_sys_district.csv'))
# x_train, y_label = tf.compat.v1.decode_csv(hotelDescs, record_defaults=tf.int64)


# print(y_label)
# labeled_dataset = lines_dataset.map(lambda ex: labeler(ex, 1))
# labeled_data_sets.append(labeled_dataset)
# tokenizer = tfds.features.text.Tokenizer()

# vocabulary_set = set()
# for text_tensor, _ in all_labeled_data:
#   some_tokens = tokenizer.tokenize(text_tensor.numpy())
#   vocabulary_set.update(some_tokens)

# vocab_size = len(vocabulary_set)
# vocab_size

文件  select_description_from_sys_district.csv 存在。盛宴大幕拉开了。


ValueError: could not convert string to float: '2019年开业60间房。上海时生隅园林文化酒店：2017年的秋末，时生隅初见。彼时的心愿，想要在快节奏的都市，寻一处“讲诉时光和生命的角落”。不问对错，不闻浮沉。这便是“时生隅”的由来。 这一次，我们秉承初心，在闹中取静的川沙地铁站商圈，觅得一方天地—充满江南气息的园林，叶园。长廊湖景，古雅庭院。这里淡雅而大气，是快节奏与民俗文化的交融，这里幽静而明快，是远道而来亦或小憩而居的别样天地。时生隅的新老朋友，我们在叶园，期待与您共襄当下景，把时光言欢。'

811008/807992 [==============================] - 0s 0us/step


'/root/.keras/datasets'

In [9]:
def labeler(example, index):
  return example, tf.cast(index, tf.int64)  

labeled_data_sets = []

for i, file_name in enumerate(FILE_NAMES):
  lines_dataset = tf.data.TextLineDataset(os.path.join(parent_dir, file_name))
  labeled_dataset = lines_dataset.map(lambda ex: labeler(ex, i))
  labeled_data_sets.append(labeled_dataset)
print(labeled_data_sets)
BUFFER_SIZE = 50000
BATCH_SIZE = 64
TAKE_SIZE = 5000
all_labeled_data = labeled_data_sets[0]
for labeled_dataset in labeled_data_sets[1:]:
  all_labeled_data = all_labeled_data.concatenate(labeled_dataset)
  
all_labeled_data = all_labeled_data.shuffle(
    BUFFER_SIZE, reshuffle_each_iteration=False)
for ex in all_labeled_data.take(5):
  print(ex)

[<MapDataset shapes: ((), ()), types: (tf.string, tf.int64)>, <MapDataset shapes: ((), ()), types: (tf.string, tf.int64)>, <MapDataset shapes: ((), ()), types: (tf.string, tf.int64)>]
(<tf.Tensor: shape=(), dtype=string, numpy=b'daughter of mighty Saturn, say what you want, and I will do it for you'>, <tf.Tensor: shape=(), dtype=int64, numpy=2>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'In yon rude host those noblest of the Greeks.'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b"Then Hector to his comrades' ranks withdrew,">, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'while his son Dolops was versed in all the ways of war. He then struck'>, <tf.Tensor: shape=(), dtype=int64, numpy=2>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'Here to abide in prospect of the fleet,'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)


In [2]:
data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

val_data = np.random.random((100, 32))
val_labels = np.random.random((100, 10))

In [6]:
model = tf.keras.Sequential([
# Adds a densely-connected layer with 64 units to the model:
layers.Dense(64, activation='relu', input_shape=(32,)),
# Add another:
# Add a softmax layer with 10 output units:
layers.Dense(10, activation='softmax')])

model.compile(optimizer=tf.keras.optimizers.Adam(0.1),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=32, batch_size=32,
          validation_data=(val_data, val_labels))

Train on 1000 samples, validate on 100 samples
Epoch 1/32
1000/1000 [==============================] - 0s 299us/sample - loss: 178.4614 - accuracy: 0.0900 - val_loss: 370.4379 - val_accuracy: 0.1400
Epoch 2/32
1000/1000 [==============================] - 0s 81us/sample - loss: 789.0940 - accuracy: 0.1160 - val_loss: 1276.2204 - val_accuracy: 0.0900
Epoch 3/32
1000/1000 [==============================] - 0s 88us/sample - loss: 1893.9300 - accuracy: 0.0840 - val_loss: 2265.7230 - val_accuracy: 0.0800
Epoch 4/32
1000/1000 [==============================] - 0s 99us/sample - loss: 2883.4460 - accuracy: 0.0970 - val_loss: 3304.5038 - val_accuracy: 0.1200
Epoch 5/32
1000/1000 [==============================] - 0s 78us/sample - loss: 3217.7243 - accuracy: 0.1100 - val_loss: 3082.2223 - val_accuracy: 0.0700
Epoch 6/32
1000/1000 [==============================] - 0s 76us/sample - loss: 3250.8884 - accuracy: 0.0700 - val_loss: 3111.5793 - val_accuracy: 0.1200
Epoch 7/32
1000/1000 [===============